[[items]]
certification="CompTIA A+"
issuer="CompTIA"
date="2025"
[[items]]
certification="CompTIA Network+"
issuer="CompTIA"
date="2025"
[[items]]
certification="CompTIA Security+"
issuer="CompTIA"
date="2025"
[[items]]
certification="ITILv4 Foundation"
issuer="Axelos"
date="2024"
