[[items]]
position="IT Support Specialist(Volunteer)"
date="2022 - Present"
employer="self"
description="Provided IT support to friends and family while continuously upgrading skills through formal IT certification programs and informal self-designed projects."
bullets=[
    "Built, maintained, or troubleshot 10 computers and 2 3D printers",
    "Earned 4 IT certifications",
    "Selected as student representative by Alamo College RTW for City of San Antonio \"Listening\" event to share program feedback",
    "Assisted with basic construction and labor tasks for remodel of historical home"
]
