name="Andres Coit"
title="Help Desk or Technical Support Technician, Entry Level"
about="Linux and tech enthusiast with experience building & troubleshooting machines from a young age. Bachelor's degree in Electrical Engineering with 30+ IT-related credits from UTSA."
email="andrescoit@gmail.com"
location="San Antonio, TX"
linkedin="linkedin.com/in/andrescoit"
