[[items]]
skill="Microsoft Office"
percent="95%"
[[items]]
skill="Linux"
percent="88%"
[[items]]
skill="Networking Technology"
percent="85%"
[[items]]
skill="Computer Hardware"
percent="85%"
[[items]]
skill="Bash"
percent="80%"
[[items]]
skill="Python"
percent="75%"
[[items]]
skill="Operating Systems"
percent="66%"
[[items]]
skill="Administrative Tools"
percent="60%"
